FROM python:3.11-alpine

RUN apk add --no-cache nss freetype harfbuzz ca-certificates ttf-freefont
RUN apk add --no-cache chromium
RUN apk add --no-cache chromium-chromedriver

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN adduser -D appuser && chown -R appuser /app
USER appuser

CMD ["python", "verificar_reniec.py"]
