FROM python:3.11-alpine AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

FROM python:3.11-alpine
WORKDIR /app

RUN apk add --no-cache nss freetype harfbuzz ca-certificates ttf-freefont
RUN apk add --no-cache chromium
RUN apk add --no-cache chromium-chromedriver

COPY --from=builder /root/.local /root/.local
COPY . .

ENV PATH=/root/.local/bin:$PATH

CMD ["python", "verificar_reniec.py"]
