# Etapa 1: Builder
FROM python:3.11-alpine AS builder
WORKDIR /app
COPY datos.csv .
COPY verificar_reniec.py .

# Etapa 2: Final
FROM python:3.11-alpine
WORKDIR /app
COPY --from=builder /app .
RUN adduser -D appuser && chown -R appuser /app
USER appuser
CMD ["python", "verificar_reniec.py"]
